# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaiRun.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1015, 608)
        MainWindow.setMinimumSize(QtCore.QSize(1015, 608))
        MainWindow.setMaximumSize(QtCore.QSize(1015, 608))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1011, 581))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.infoLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.infoLabel.setEnabled(True)
        self.infoLabel.setMinimumSize(QtCore.QSize(800, 30))
        self.infoLabel.setMaximumSize(QtCore.QSize(800, 30))
        self.infoLabel.setStyleSheet("border:1px solid black;")
        self.infoLabel.setObjectName("infoLabel")
        self.gridLayout.addWidget(self.infoLabel, 0, 0, 1, 1)
        self.videoLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.videoLabel.setMinimumSize(QtCore.QSize(800, 500))
        self.videoLabel.setMaximumSize(QtCore.QSize(800, 500))
        self.videoLabel.setStyleSheet("background-color: rgb(94, 94, 94);\n"
"border:1px solid black;")
        self.videoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videoLabel.setObjectName("videoLabel")
        self.gridLayout.addWidget(self.videoLabel, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(200, 30))
        self.label_2.setMaximumSize(QtCore.QSize(200, 30))
        self.label_2.setStyleSheet("border:1px solid black;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.LPNLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LPNLabel.setMinimumSize(QtCore.QSize(0, 230))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LPNLabel.setFont(font)
        self.LPNLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LPNLabel.setObjectName("LPNLabel")
        self.verticalLayout.addWidget(self.LPNLabel)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(200, 30))
        self.label_3.setMaximumSize(QtCore.QSize(200, 30))
        self.label_3.setStyleSheet("border:1px solid black;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.proLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.proLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.proLabel.setObjectName("proLabel")
        self.verticalLayout.addWidget(self.proLabel)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(200, 30))
        self.label_4.setMaximumSize(QtCore.QSize(200, 30))
        self.label_4.setStyleSheet("border:1px solid black;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.typeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.typeLabel.setText("")
        self.typeLabel.setObjectName("typeLabel")
        self.verticalLayout.addWidget(self.typeLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_vcr = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_vcr.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_vcr.setMaximumSize(QtCore.QSize(90, 30))
        self.pushButton_vcr.setObjectName("pushButton_vcr")
        self.horizontalLayout_3.addWidget(self.pushButton_vcr)
        self.pushButton_cap = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cap.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_cap.setMaximumSize(QtCore.QSize(90, 30))
        self.pushButton_cap.setObjectName("pushButton_cap")
        self.horizontalLayout_3.addWidget(self.pushButton_cap)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.timeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.timeLabel.setStyleSheet("border:1px solid black;")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout.addWidget(self.timeLabel, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mysqlLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mysqlLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.mysqlLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mysqlLabel.setStyleSheet("border:1px solid black;")
        self.mysqlLabel.setObjectName("mysqlLabel")
        self.horizontalLayout_2.addWidget(self.mysqlLabel)
        self.stateLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.stateLabel.setStyleSheet("border:1px solid black;")
        self.stateLabel.setObjectName("stateLabel")
        self.horizontalLayout_2.addWidget(self.stateLabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionUSB = QtWidgets.QAction(MainWindow)
        self.actionUSB.setObjectName("actionUSB")
        self.actionRTSP = QtWidgets.QAction(MainWindow)
        self.actionRTSP.setObjectName("actionRTSP")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu.addAction(self.actionUSB)
        self.menu.addAction(self.actionRTSP)
        self.menu.addAction(self.actionClose)
        self.menuhelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "佰润车牌识别系统"))
        self.pushButton_2.setText(_translate("MainWindow", "打开相机"))
        self.pushButton.setText(_translate("MainWindow", "关闭"))
        self.infoLabel.setText(_translate("MainWindow", "当前已连接摄像头：USB "))
        self.videoLabel.setText(_translate("MainWindow", "未能获取到图像"))
        self.label_2.setText(_translate("MainWindow", "获取到的车牌号码为："))
        self.LPNLabel.setText(_translate("MainWindow", "暂无数据"))
        self.label_3.setText(_translate("MainWindow", "识别概率最大为："))
        self.proLabel.setText(_translate("MainWindow", "暂无数据"))
        self.label_4.setText(_translate("MainWindow", "车牌类型："))
        self.pushButton_vcr.setText(_translate("MainWindow", "开始录像"))
        self.pushButton_cap.setText(_translate("MainWindow", "播报开启"))
        self.timeLabel.setText(_translate("MainWindow", "2018-06-21 08:00"))
        self.mysqlLabel.setText(_translate("MainWindow", "数据库未连接"))
        self.stateLabel.setText(_translate("MainWindow", "上一次识别的车牌为：贵F18103"))
        self.menu.setTitle(_translate("MainWindow", "设备"))
        self.menuhelp.setTitle(_translate("MainWindow", "帮助"))
        self.actionUSB.setText(_translate("MainWindow", "USB"))
        self.actionRTSP.setText(_translate("MainWindow", "RTSP"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

